export const userTypes = {
    UPDATE_USER_DETAILS:'UPDATE_USER_DETAILS',
    UPDATE_USER_SUGGESTION:'UPDATE_USER_SUGGESTION',
    UPDATE_USER_IS_LOGGED_IN:'UPDATE_USER_IS_LOGGED_IN',
    UPDATE_USER_LOGIN_ERROR:'UPDATE_USER_LOGIN_ERROR'
};